name: ai_compliance_assessment
description: "Polis AI Compliance Risk Assessment Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # State Management
  flutter_riverpod: ^2.4.9

  # Navigation
  go_router: ^16.1.0

  # Forms & Validation
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  flutter_localizations:
    sdk: flutter

  # Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4   # <— una sola volta, SOLO qui

  # RUNTIME deps (spostate qui)
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  intl: ^0.20.2
  uuid: ^4.2.2
  collection: ^1.18.0
  pdf: ^3.10.7
  printing: ^5.12.0
  syncfusion_flutter_charts: ^30.2.4
  file_picker: ^10.3.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.9.2
