name: ai_compliance_assessment
description: "Polis AI Compliance Risk Assessment Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # State Management
  flutter_riverpod: ^2.4.9

  # Navigation
  go_router: ^16.1.0

  # Forms & Validation
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  flutter_localizations:
    sdk: flutter

  # Data Models - VERSIONI FISSE PER COMPATIBILITÀ
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Local Storage
  shared_preferences: ^2.2.2

  # Network
  dio: ^5.4.0

  # Utils
  intl: ^0.20.2
  uuid: ^4.2.2
  collection: ^1.18.0

  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.12.0

  # Charts
  syncfusion_flutter_charts: ^30.2.4

  # File Handling
  file_picker: ^10.3.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generation - VERSIONI FISSE PER COMPATIBILITÀ
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/images/
    - assets/icons/